version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: paperpos-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: paperpos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: paperpos-web
    restart: always
    ports:
      - "3005:3000"
    environment:
      # 👈 Fíjate cómo la URL ya no dice "localhost", sino "db" (el nombre del contenedor de arriba)
      - DATABASE_URL=postgresql://admin:adminpassword@db:5432/paperpos?schema=public
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=super_secreto_paperpos_2026_muy_seguro_123
    depends_on:
      - db # 👈 Le decimos a Docker: "No enciendas la web hasta que la BD esté lista"

volumes:
  postgres_data: