services:
  db:
    image: postgres:15-alpine
    container_name: paperpos-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: paperpos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: paperpos-web
    restart: always
    ports:
      - "3005:3000"
    environment:
      - DATABASE_URL=postgresql://admin:adminpassword@db:5432/paperpos?schema=public
      - NEXTAUTH_URL=https://papeleria-galindos.com
      - NEXTAUTH_SECRET=super_secreto_paperpos_2026_muy_seguro_123
    depends_on:
      - db

  tunnel:
    image: cloudflare/cloudflared
    container_name: paperpos-tunnel
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiOTg1NzhkMmYwNTExM2M0MGRhNjZmZTUzOTQ4MWU0MGQiLCJ0IjoiZmIxMmVmOWYtYWE2MC00NDBlLWJmYjItODQxZTcxYTU5ZGE5IiwicyI6Ik5EZGtaVGN3Wm1NdE56QTJNeTAwWlRVeUxXRTNNR0V0T1dVek56STJORGxpWmpJNCJ9
    depends_on:
      - web

volumes:
  postgres_data: